### PR TITLE
Update cli initialization

### PR DESCRIPTION
**Pull request by anselal**

### CODE REVIEW

**Comment by mjhea0** [comment]
Line 13 can just be removed, but you will need to revert the changes to line 14 - `cli = FlaskGroup(create_app=create_app)`

**Comment by anselal** [comment]
You are right about line 14 but I think we can keep line 13 and add something like:

```python
@app.shell_context_processor
def make_shell_context():
    return dict(app=app, db=db)
```

**Comment by mjhea0** [comment]
What's the advantage in doing that in *manage.py* vs https://github.com/realpython/flask-skeleton/blob/master/project/server/__init__.py#L78

**Comment by anselal** [comment]
I think because `shell_context_processor` is somehow part of the cli commands it would be prettier if all related "commands" were in one file.

**Comment by mjhea0** [comment]
Can you remove it from the *\_\_init\_\_.py* file then?

**Comment by mjhea0** [comment]
👍

**Comment by anselal** [comment]
:tada:

**Comment by anselal** [comment]
Question:

We added some variables in the shell context, right ? Are those variables only callable when we call `flask shell` instead of `python manager.py shell` ?

**Comment by mjhea0** [comment]
You should have access:

```
$ FLASK_DEBUG=1 && python manage.py shell
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
App: project.server
Instance: /Users/michael.herman/repos/realpython/flask-skeleton/instance
>>> app
<Flask 'project.server'>
>>> app.db
```

**Comment by anselal** [comment]
I should but I don't.

**Comment by mjhea0** [comment]
Not sure. What are you trying to do?

**Comment by anselal** [comment]
It seems that after I moved the `shell_context_processor` outside the create_app(), the variables are not accessible. Maybe it is because we call the `shell_context_processor` after the `cli` is initialized.

I think that you were right to call the `shell_context_processor` inside  `create_app`.

So I guess this PR is invalid. At least we learned something out of it.

**Comment by anselal** [comment]
I was trying to access `db` from shell as well as some models.

**Comment by anselal** [comment]
Shall I create another commit and revert the changes or will you do it ?
Unless there is a way to fix this.

**Comment by mjhea0** [comment]
I don't think it was working the way you want before either.

**Comment by anselal** [comment]
It did. I tested it. The shell autoloads all the variables you set. In our case the app and the db but you can add your models as well. This is helpful while debugging so you don't need to import the db and models !!!

Just try it out !!!

**Comment by mjhea0** [comment]
Can you issue a new PR?

**Comment by anselal** [comment]
Sure.

**Pull request merged**
